import { CalendarClock, RadioTower } from "lucide-react";

export default function InstructorClassesPage() {
  return (
    <main className="mx-auto min-h-screen max-w-7xl px-5 py-8 md:px-8">
      <h1 className="text-3xl font-semibold">Live classes</h1>
      <section className="mt-8 grid gap-4 md:grid-cols-2">
        <article className="rounded-lg border border-[var(--line)] bg-white p-5">
          <CalendarClock className="mb-3 text-[var(--brand)]" aria-hidden="true" />
          <h2 className="font-semibold">Join window</h2>
          <p className="mt-2 text-sm leading-6 text-[var(--muted)]">
            Instructors can enter up to 15 minutes before scheduled start.
          </p>
        </article>
        <article className="rounded-lg border border-[var(--line)] bg-white p-5">
          <RadioTower className="mb-3 text-[var(--brand)]" aria-hidden="true" />
          <h2 className="font-semibold">LiveKit token</h2>
          <p className="mt-2 text-sm leading-6 text-[var(--muted)]">
            Tokens are scoped to the assigned course room and generated by the API.
          </p>
        </article>
      </section>
    </main>
  );
}

